### ISSUE TITLE
generate_reports throwing errors

### ISSUE THREAD

**Issue by doug-leasure** [OxfordDemSci/gwasdiversitymonitor#81]
The `generate_reports()` function is throwing an error in generate_data.py (`dev` branch) when it is running in the gwas_data docker container. 

Use `$ docker logs gwas_data` to get the following traceback:
```
Traceback (most recent call last):
  File "/app/generate_reports.py", line 146, in generate_reports
    agency_list = get_agency_list(data_path)
  File "/app/generate_reports.py", line 24, in get_agency_list
    with open(agency_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/app/data/pubmed/agency_list.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "generate_data.py", line 1439, in <module>
    generate_reports(data_path, reports_path, diversity_logger)
  File "/app/generate_reports.py", line 153, in generate_reports
    diversity_logger.debug('Build of the reports: Failed with exception: ', e)
Message: 'Build of the reports: Failed with exception: '
Arguments: (FileNotFoundError(2, 'No such file or directory'),)
```

**Comment by doug-leasure** [comment]
The error from the traceback above seems to be resolved by moving the reports directory into the data directory so that it is available from inside the docker container "gwas_flask" (i.e. the data folder is mounted inside the container). 

generate_reports is now throwing the following error associated with the `execute_tex()` function in `generate_reports.py`:

```
Traceback (most recent call last):
  File "/app/generate_reports.py", line 149, in generate_reports
    execute_tex(reports_path, data_path, agency_list)
  File "/app/generate_reports.py", line 129, in execute_tex
Traceback (most recent call last):
  File "/app/generate_reports.py", line 149, in generate_reports
    execute_tex(reports_path, data_path, agency_list)
  File "/app/generate_reports.py", line 129, in execute_tex
    doc.generate_pdf(path, compiler='pdflatex', clean_tex=False, clean=True)
  File "/usr/local/lib/python3.8/site-packages/pylatex/document.py", line 298, in generate_pdf
    raise(CompilerError(
pylatex.errors.CompilerError: No LaTex compiler was found
Either specify a LaTex compiler or make sure you have latexmk or pdfLaTex installed.

    doc.generate_pdf(path, compiler='pdflatex', clean_tex=False, clean=True)
  File "/usr/local/lib/python3.8/site-packages/pylatex/document.py", line 298, in generate_pdf
    raise(CompilerError(
pylatex.errors.CompilerError: No LaTex compiler was found
Either specify a LaTex compiler or make sure you have latexmk or pdfLaTex installed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "generate_data.py", line 1439, in <module>
    generate_reports(data_path, reports_path, diversity_logger)
  File "/app/generate_reports.py", line 153, in generate_reports
    diversity_logger.debug('Build of the reports: Failed with exception: ', e)
Message: 'Build of the reports: Failed with exception: '
Arguments: (CompilerError('No LaTex compiler was found\nEither specify a LaTex compiler or make sure you have latexmk or pdfLaTex installed.'),)
```

**Comment by crahal** [comment]
See the dev branch readme.md to solve this:

```
Version 2.0 of the application ('By Funder') also generates reports using the [pylatex](https://jeltef.github.io/PyLaTeX/current/) module. For the generate_data.py script to successful call the generate_reports.py module, you'll need an active LaTeX installation. For that, we recommend ['TeX Live'](https://tug.org/texlive/).
```

Something like `sudo apt install texlive` should do the trick; this could also be added to the dev branch readme.

**Comment by doug-leasure** [comment]
Exactly! Commit [6b0540b](https://github.com/OxfordDemSci/gwasdiversitymonitor/commit/6b0540baf55b600ec7568122d561ee2bbb0f86a4) modified the Docker file of the gwas_data container to install `latexmk` and `texlive-latex-extra` in the container. Pull request #82 will resolve this issue.

**Comment by crahal** [comment]
Also closed, same reason as #84
